spring:
    application:
        name: eureka-server
    cloud:
        config:
            profile: ${CONFIG_PROFILE}
    config:
        import: configserver:http://localhost:8888,optional:file:.env[.properties]