spring:
    application:
        name: invoice-service
    cloud:
        config:
            profile: ${CONFIG_PROFILE}
    config:
        import: configserver:http://localhost:8888,optional:file:.env[.properties]
management:
    endpoint:
        metrics:
            enabled: true
        prometheus:
            enabled: true
    endpoints:
        web:
            exposure:
                include: '*'
    metrics:
        export:
            prometheus:
                enabled: true